apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-go
  template:
    metadata:
      labels:
        app: api-go
    spec:
      containers:
        - name: go-api
          image: leonardofronza/api-go-gurizes-app:lasted
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-loadbalancer
  labels:
    app: api-go
    component: apiserver
    provider: kubernetes
spec:
  selector:
    app: api-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2

