basePath: /
info:
  contact: {}
  description: Esta API retorna uma lista aleat贸ria de inteiros.
  title: API de Lista Aleat贸ria com Swagger
paths:
  /random-list:
    get:
      consumes:
      - application/json
      description: Retorna uma lista aleat贸ria de inteiros.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Retorna uma lista aleat贸ria
swagger: "2.0"
